# Generated by Django 5.2.4 on 2025-08-01 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(help_text='Número de teléfono del usuario (ej: +5403535123123)', max_length=20)),
                ('categoria', models.CharField(help_text='Categoría del gasto (ej: comida, transporte, Netflix)', max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del gasto', max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del registro del gasto')),
                ('mensaje_original', models.TextField(help_text='Mensaje original recibido por WhatsApp')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
    ]
